Allow passing codec options to decoder
klarna/avlizer pull request #17
Opened 2021-07-02 08:48 UTC by 4tyTwo

The API should not have been changed as a result of this change apart from one side-effect: the library will no longer support string fingerprints in `avlizer_confluent:make_decoder/2` (because strings will pattern match as lists and be treated like codec_options. I would emphasize that the use of strings there was against the type spec.

2021-07-02 08:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/klarna/avlizer?pullRequest=17) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/klarna/avlizer?pullRequest=17) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/klarna/avlizer?pullRequest=17) it.</sub>

2021-07-08 14:13 UTC, mikpe commented on src/avlizer_confluent.erl
> +  do_make_decoder({Name, Fp}, ?DEFAULT_CODEC_OPTIONS).
Unfortunately I think the specs are wrong. The code very explicitly allows and handles fingerprints as plain lists (see `unify_ref/1` and `fp_to_subject/2`) and I think we need to preserve that. So when the 2nd parameter here is a list, you need to perform a test to see if it's a fingerprint or not, for example:
```
make_decoder(Ref, FpOrCodecOptions) when is_list(FpOrCodecOptions) ->
  case is_fp(FpOrCodecOptions) of
    true -> ... ;
    false -> ...
  end;
...
is_fp(List) ->
  try
    _ = iolist_to_binary(fp),
    true
  catch
    error:badarg ->
      false
  end.
```
and similar in the other API entry points.

Alternatively only handle CodecOptions in the new `/3` entry points, but allow passing in e.g. `false` as Fp and in that case don't include that in the Ref.

Maybe @zmstone has some input, as the author of this?

2021-07-12 11:51 UTC, dszoboszlay requested changes
Please fix the few minor things I indicated in type specs and head comments getting out of sync with code!

2021-07-12 11:51 UTC, dszoboszlay commented on src/avlizer_confluent.erl
> +-spec make_decoder(name(), fp() | codec_options()) -> avro:simple_decoder().
The correct type spec is similar to `get_decored/2`'s:
```erlang
-spec make_decoder(ref(), codec_options()) -> avro:simple_decoder();
                  (name(), fp()) -> avro:simple_decoder().
```

2021-07-12 11:51 UTC, dszoboszlay commented on src/avlizer_confluent.erl
>  %% @doc Decode untagged payload or with a given schema reference.
Mention the new use too: decode tagged payload with custom codec options.

2021-07-12 11:51 UTC, dszoboszlay commented on src/avlizer_confluent.erl
>    decode(RegId, Payload).
Consider changing `decode/1` to:

```erlang
decode(Bin) ->
  decode(Bin, ?DEFAULT_CODEC_OPTIONS).
```

2021-07-12 11:51 UTC, dszoboszlay commented on src/avlizer_confluent.erl
>  %% @doc Decode avro binary with given schema name and fingerprint.
Mention the new use too: decode avro binary with given schema reference and custom codec options.

2021-07-12 13:31 UTC, dszoboszlay approved these changes

2021-07-12 13:33 UTC, merged